export const emojiMap = {
  "icon_angry.gif": "😡",
  "icon_confused.gif": "🤷‍♀️",
  "icon_cool.gif": "😎",
  "icon_cry.gif": "😢",
  "icon_cry2.gif": "😭",
  "icon_cute.gif": "🥰",
  "icon_eek.gif": "😲",
  "icon_heart.gif": "❤️",
  "icon_idea.gif": "💡",
  "icon_lol.gif": "😂",
  "icon_music.gif": "🎵",
  "icon_no.gif": "❌",
  "icon_razz.gif": "😛",
  "icon_redface.gif": "😳",
  "icon_rolleyes.gif": "🙄",
  "icon_sad.gif": "😞",
  "icon_smile.gif": "🙂",
  "icon_star.gif": "⭐️",
  "icon_stun.gif": "😵‍💫",
  "icon_sweat.gif": "😅",
  "icon_wink.gif": "😜",
  "icon_yes.gif": "👍",
  "icon_yiw.gif": "❓",
  "icon_zzz.gif": "💤"
};
